name: tour_guide
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_acrylic: ^1.1.0
  flutter_html: ^3.0.0-beta.2

  fluent_ui: ^4.6.2
  go_router: ^8.1.0

  window_manager: ^0.3.4
  
  flutter:
    sdk: flutter
  system_theme: ^2.2.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    # Add assets from the images directory to the application.
    - assets/images/
